### ISSUE TITLE
How can I disable it?

### ISSUE THREAD

**Issue by Lingxuan-Ye** [next-theme/hexo-next-fireworks#2]
Thanks for your plugin! I would like to know what I should do if I want to disable this plugin without uninstallation (I wish it be enabled only on some special holidays).

感谢你的插件！我想知道怎样设置才能做到关闭点击特效的同时不用卸载该插件（我只想在一些特殊时候开启点击特效）。

**Comment by stevenjoezhang** [comment]
在 `_config.yml` 里面这样设置可以关闭

```
fireworks:
  enable: true
```
这个功能是刚刚加上的，你可能需要重装一下插件

**Comment by Lingxuan-Ye** [comment]
谢谢！

**Comment by Lingxuan-Ye** [comment]
报了个错误：

```
ERROR Plugin load failed: hexo-next-fireworks
    ReferenceError: deepMerge is not defined
```

**Comment by stevenjoezhang** [comment]
忘记回复了，在这里修复了 https://github.com/next-theme/hexo-next-fireworks/commit/c2f98bdd41461084e8bf5d0190f6a6a9fdee99eb 再重装一下插件就行
